# Generated by Django 2.0 on 2018-05-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='url_slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
