# Generated by Django 2.0 on 2018-05-30 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userinfo_url_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='url_slug',
            new_name='slug',
        ),
    ]
