# Generated by Django 2.0 on 2018-05-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('birth', models.DateField()),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男')])),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('birth', models.DateField()),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男')])),
                ('is_married', models.IntegerField(choices=[(0, '未婚'), (1, '已婚')])),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(to='school.Teacher'),
        ),
    ]
