# Generated by Django 2.0 on 2018-05-23 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('deptNo', models.AutoField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=50, null=True)),
                ('loc', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'dept',
            },
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('empNo', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('ename', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('job', models.CharField(max_length=50, null=True)),
                ('hireDate', models.DateField(null=True)),
                ('sal', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('comm', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男')])),
                ('isValid', models.IntegerField(choices=[(0, '无效'), (1, '有效')], db_column='is_valid', default=1)),
                ('dept', models.ForeignKey(db_column='deptno', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Dept')),
                ('mgr', models.ForeignKey(db_column='mgr', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Emp')),
            ],
            options={
                'db_table': 'emp',
                'ordering': ['empNo'],
            },
        ),
        migrations.CreateModel(
            name='SaleGrade',
            fields=[
                ('grade', models.AutoField(primary_key=True, serialize=False)),
                ('losal', models.IntegerField()),
                ('hisal', models.IntegerField()),
            ],
        ),
    ]
