# Generated by Django 2.0 on 2018-05-31 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emp',
            options={},
        ),
        migrations.AlterModelTable(
            name='salegrade',
            table='salegrade',
        ),
    ]
